@doc raw"""
    write_capacity_value(path::AbstractString,
                         inputs::Dict,
                         setup::Dict,
                         EP::Model)

This is the value of the derated capacities of different types of resources multiplied by the power generated by each of them 

# Arguments
- path::AbstractString: Path to the directory where the file will be written.
- inputs::Dict: Dictionary of input data.
- setup::Dict: Dictionary of setup data.
- EP::Model: EnergyModel object.

# Results
- A CSV file named "CapacityValue.csv" is written to the directory specified by `path`.
"""
function write_capacity_value_peakload(path::AbstractString, inputs::Dict, setup::Dict, EP::Model)
    gen   = inputs["RESOURCES"]
    zones = zone_id.(gen)

    G = inputs["G"]
    THERM_ALL = inputs["THERM_ALL"]
    VRE       = inputs["VRE"]
    HYDRO_RES = inputs["HYDRO_RES"]
    STOR_ALL  = inputs["STOR_ALL"]
    FLEX      = inputs["FLEX"]
    MUST_RUN  = inputs["MUST_RUN"]
    VRE_STOR  = inputs["VRE_STOR"]

    scale_factor = setup["ParameterScale"] == 1 ? ModelScalingFactor : 1
    eTotalCap = value.(EP[:eTotalCap])

    minimum_plant_size = 1 # MW
    large_plants = findall(>=(minimum_plant_size), eTotalCap * scale_factor)

    THERM_ALL_EX = intersect(THERM_ALL, large_plants)
    VRE_EX       = intersect(VRE, large_plants)
    HYDRO_RES_EX = intersect(HYDRO_RES, large_plants)
    STOR_ALL_EX  = intersect(STOR_ALL, large_plants)
    FLEX_EX      = intersect(FLEX, large_plants)
    MUST_RUN_EX  = intersect(MUST_RUN, large_plants)
    VRE_STOR_EX  = intersect(VRE_STOR, large_plants)

    dfCapValue = DataFrame()

    # ========= peakload =========
    for i in 1:inputs["NCapacityReserveMargin"]

        capvalue = zeros(G)

        crm_derate(y) = derating_factor(gen[y], tag=i)

        # --- THERMAL ---
        capvalue[THERM_ALL_EX] = [
            thermal_plant_effective_capacity_peakload(EP, inputs, y, i)
            for y in THERM_ALL_EX
        ]

        # --- VRE ---
        capvalue[VRE_EX] = [crm_derate(y) for y in VRE_EX] .* eTotalCap[VRE_EX]

        # --- MUST RUN ---
        capvalue[MUST_RUN_EX] = [crm_derate(y) for y in MUST_RUN_EX] .* eTotalCap[MUST_RUN_EX]

        # --- HYDRO ---
        capvalue[HYDRO_RES_EX] = [crm_derate(y) for y in HYDRO_RES_EX] .* eTotalCap[HYDRO_RES_EX]

        # --- STORAGE ---
        if !isempty(STOR_ALL_EX)
            capvalue[STOR_ALL_EX] = [crm_derate(y) for y in STOR_ALL_EX] .* eTotalCap[STOR_ALL_EX]
        end

        # --- FLEX ---
        if !isempty(FLEX_EX)
            capvalue[FLEX_EX] = [crm_derate(y) for y in FLEX_EX] .* eTotalCap[FLEX_EX]
        end

        # --- VRE-STOR ---
        if !isempty(VRE_STOR_EX)
            capvalue[VRE_STOR_EX] = [crm_derate(y) for y in VRE_STOR_EX] .* eTotalCap[VRE_STOR_EX]
        end

        temp_dfCapValue = DataFrame(
            Resource = inputs["RESOURCE_NAMES"],
            Zone     = zones,
            Reserve  = fill(Symbol("CapRes_$i"), G),
            Value    = capvalue
        )

        append!(dfCapValue, temp_dfCapValue)
    end

    write_simple_csv(joinpath(path, "CapacityValue_peakload.csv"), dfCapValue)
end


function capacity_reserve_margin_price_peakload(EP::Model, inputs::Dict, setup::Dict, capres_zone::Int)
    scale_factor = setup["ParameterScale"] == 1 ? ModelScalingFactor : 1.0
    sp = dual(EP[:cCapacityResMargin][capres_zone])
    return max(0.0, sp) * scale_factor
end